
optimus_joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

optimus_FR_outer_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: 'FR_outer_wheel_joint'
    pid: {p: 1.0, i: 1.0, d: 1.0}

optimus_FL_outer_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: 'FL_outer_wheel_joint'
    pid: {p: 1.0, i: 1.0, d: 1.0}

optimus_FR_inner_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: 'FR_inner_wheel_joint'
    pid: {p: 1.0, i: 1.0, d: 1.0}

optimus_FL_inner_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: 'FL_inner_wheel_joint'
    pid: {p: 1.0, i: 1.0, d: 1.0}

optimus_FR_outer_wheel_connector_controller:
    type: position_controllers/JointPositionController
    joint: 'FR_outer_wheel_connector_joint'
    pid: {p: 1.0, i: 0.0, d: 0.0}

optimus_FL_outer_wheel_connector_controller:
    type: position_controllers/JointPositionController
    joint: 'FL_outer_wheel_connector_joint'
    pid: {p: 1.0, i: 0.0, d: 0.0}

optimus_FR_inner_wheel_connector_controller:
    type: position_controllers/JointPositionController
    joint: 'FR_inner_wheel_connector_joint'
    pid: {p: 1.0, i: 0.0, d: 0.0}

optimus_FL_inner_wheel_connector_controller:
    type: position_controllers/JointPositionController
    joint: 'FL_inner_wheel_connector_joint'
    pid: {p: 1.0, i: 0.0, d: 0.0}